version: '3'

services:
  ai-agent:
    build: .
    container_name: ai-agent
    ports:
      - "3002:3002"
    environment:
      - PORT=3002
      - API_BASE_URL=${API_BASE_URL:-http://localhost:3000/api}
      - NODE_ENV=${NODE_ENV:-development}
    restart: unless-stopped 